name: Sync with Upstream

on:
  schedule:
    # Run daily at 1:00 AM GMT
    - cron: '0 1 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/musistudio/claude-code-router.git || true
          git fetch upstream
      
      - name: Sync with upstream
        run: |
          # Fetch the latest changes from upstream
          git fetch upstream main
          
          # Check if there are any differences
          if git diff --quiet HEAD upstream/main; then
            echo "No changes to sync"
            exit 0
          fi
          
          # Merge upstream changes
          git merge upstream/main --no-edit || {
            echo "Merge conflict detected. Manual intervention required."
            exit 1
          }
          
          # Push changes to origin
          git push origin main
      
      - name: Create Issue on Conflict
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Upstream Sync Failed - Manual Intervention Required',
              body: `The automated upstream sync failed, likely due to merge conflicts.
              
              Please manually sync with the upstream repository:
              1. \`git remote add upstream https://github.com/musistudio/claude-code-router.git\`
              2. \`git fetch upstream main\`
              3. \`git merge upstream/main\`
              4. Resolve any conflicts
              5. \`git push origin main\`
              
              Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`
            })